#!/usr/bin/env python3
"""
Report Generator Module

Generates markdown benchmark reports.
"""

from pathlib import Path
from typing import Dict, Any
from datetime import datetime


def generate_report(rankings: Dict, reports_dir: Path) -> Path:
    """Generate a markdown benchmark report."""

    report_date = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"benchmark-report-{report_date}.md"

    # Calculate total skills tested
    total_skills = sum(len(cat['skills']) for cat in rankings['categories'])

    report_content = f"""# Skill Arena Benchmark Report

**Generated:** {report_date}

## Executive Summary

- **Total Skills Tested:** {total_skills}
- **Categories:** {len(rankings['categories'])}
- **Test Cases:** {len(rankings['categories']) * 5}  # Estimated

---

## 🏆 Winners by Category (Top 3)

"""

    for category in rankings['categories']:
        if category.get('winner'):
            winner = category['winner']
            report_content += f"""### {category['category'].title()}

| Rank | Skill | Speed | Quality | Maintainability | Total |
|------|-------|-------|---------|-----------------|-------|
"""
            # Top 3 skills
            top_skills = category['skills'][:3]
            for i, skill in enumerate(top_skills, 1):
                medal = "🥇" if i == 1 else "🥈" if i == 2 else "🥉" if i == 3 else ""
                bold = "**" if i == 1 else ""
                report_content += f"""| {i}{medal} | {bold}{skill['skill_name']}{bold} | {skill['scores']['speed']:.1f} | {skill['scores']['quality']:.1f} | {skill['scores']['maintainability']:.1f} | {bold}{skill['total_score']:.1f}{bold} |
"""
            report_content += "\n"

    report_content += f"""
---

## 📊 Overall Top 10

| Rank | Category | Skill | Speed | Quality | Maintainability | Total |
|------|----------|-------|-------|---------|-----------------|-------|
"""

    for i, skill in enumerate(rankings['overall'][:10], 1):
        medal = "🥇" if i == 1 else "🥈" if i == 2 else "🥉" if i == 3 else ""
        report_content += f"| {i}{medal} | {skill['category'].title()} | {skill['skill_name']} | {skill['scores']['speed']:.1f} | {skill['scores']['quality']:.1f} | {skill['scores']['maintainability']:.1f} | **{skill['total_score']:.1f}** |\n"

    report_content += f"""

---

## 📈 Category Summary

| Category | Winner | Score | Skills Count |
|----------|--------|-------|--------------|
"""

    for category in rankings['categories']:
        if category.get('winner'):
            winner = category['winner']
            skill_count = len(category['skills'])
            report_content += f"| {category['category'].title()} | {winner['skill_name']} | {winner['total_score']:.1f} | {skill_count} |\n"

    report_content += f"""

---

## 📈 Detailed Results

See individual category sections above for full rankings.

---

*Report generated by Skill Arena Benchmark Tool*
"""

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    return report_path
