#!/usr/bin/env python3
"""
Report Generator Module

Generates markdown benchmark reports.
"""

from pathlib import Path
from typing import Dict, Any
from datetime import datetime


def generate_report(rankings: Dict, reports_dir: Path) -> Path:
    """Generate a markdown benchmark report."""

    report_date = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"benchmark-report-{report_date}.md"

    report_content = f"""# Skill Arena Benchmark Report

**Generated:** {report_date}

## Executive Summary

- **Total Skills Tested:** {sum(len(cat['skills']) for cat in rankings['categories'])}
- **Categories:** {len(rankings['categories'])}
- **Test Cases:** {len(rankings['categories']) * 5}  # Estimated

---

## 🏆 Winners by Category

"""

    for category in rankings['categories']:
        if category.get('winner'):
            winner = category['winner']
            report_content += f"""### 🥇 {category['category'].title()}

| Rank | Skill | Speed | Quality | Maintainability | Total |
|------|-------|-------|---------|-----------------|-------|
| 1    | **{winner['skill_name']}** | {winner['scores']['speed']:.1f} | {winner['scores']['quality']:.1f} | {winner['scores']['maintainability']:.1f} | **{winner['total_score']:.1f}** |
"""
            # Add runners-up
            for i, skill in enumerate(category['skills'][1:4], 2):
                report_content += f"""| {i}    | {skill['skill_name']} | {skill['scores']['speed']:.1f} | {skill['scores']['quality']:.1f} | {skill['scores']['maintainability']:.1f} | {skill['total_score']:.1f} |
"""
            report_content += "\n"

    report_content += f"""
---

## 📊 Overall Top 10

| Rank | Category | Skill | Total Score |
|------|----------|-------|-------------|
"""

    for i, skill in enumerate(rankings['overall'][:10], 1):
        report_content += f"| {i} | {skill['category'].title()} | {skill['skill_name']} | {skill['total_score']:.1f} |\n"

    report_content += f"""

---

## 📈 Detailed Results

See individual category sections above for full rankings.

---

*Report generated by Skill Arena Benchmark Tool*
"""

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    return report_path
